# Generated by Django 5.1 on 2024-08-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is enable'),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is enable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is enable'),
        ),
    ]
