# Generated by Django 5.1 on 2024-08-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_file_file_type_file_file_mmd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_mmd',
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'audio'), (2, 'video'), (3, 'pdf')], default=2, verbose_name='file type'),
            preserve_default=False,
        ),
    ]
